name: symfony-01
recipe: symfony
config:
  php: '8.1'
  via: nginx
  webroot: public
services:
  database:
    type: mysql
    portforward: 3307
    creds:
      user: admin
      password: admin
      database: symfony_db
  node:
    type: node:14
    build:
      - yarn install
      - npm install
tooling:
  yarn:
    service: node
  node:
    service: node
  npm:
    service: node
